# Author: Mitchell Lazarz
# Created on: 2020-10-16 11:10:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Python 2.7: flooding.py
# Description:  This code clips a floodzone shapefile to a basin shapefile then selects floodzones that are designated with the attribute "within Special Flood Hazard Areas".


# -*- coding: utf-8 -*-

# Import arcpy module
import arcpy

# Local variables are assigned:
floodzones = "floodzones"
basin = "basin"
flood_Clip_shp = "C:\\CLARK\\PythonProgramming\\CompProg_Lab1\\Results\\flood_Clip.shp"
flooding_shp = "C:\\CLARK\\PythonProgramming\\CompProg_Lab1\\Results\\flooding.shp"

# Process: Clip floodzones to basin
arcpy.Clip_analysis(floodzones, basin, flood_Clip_shp, "")

# Process: Select clipped floodzones with attribute "IN", Special Flood Hazard Areas
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\" = 'IN'")


