# Author: Mitchell Lazarz
# Creation Date: 16 October 2020
# Python 2.7: flooding.py
# Description:  This code clips a floodzones shapefile to a basin shapefile then selects floodzones that are designated with the attribute "within Special Flood Hazard Areas".


# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flooding.py
# Created on: 2020-10-16 11:10:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
floodzones = "floodzones"
basin = "basin"
flood_Clip_shp = "C:\\CLARK\\PythonProgramming\\CompProg_Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\flood_Clip.shp"
flooding_shp = "C:\\CLARK\\PythonProgramming\\CompProg_Lab1\\Data_Lab_1_Geoprocessing_ArcGIS\\flooding.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones, basin, flood_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\" = 'IN'")


